
CREATE TABLE TBL_ALUMNOS
(
   CODIGO_ALUMNO INT NOT NULL AUTO_INCREMENT,
   NUMERO_CUENTA VARCHAR(11) NOT NULL,
   PROMEDIO DOUBLE,
   CONTRASENA VARCHAR(30),
   CONSTRAINT TBL_ALUMNOS_PK PRIMARY KEY(CODIGO_ALUMNO)
);


CREATE TABLE TBL_AREA_ESPECIALIZACIONES
(
   CODIGO_ESPECIALIZACION INT NOT NULL AUTO_INCREMENT,
   DESCRIPCION VARCHAR(200) NOT NULL,
   CONSTRAINT TBL_AREA_ESPECIALIZACIONES_PK PRIMARY KEY(CODIGO_ESPECIALIZACION)
);


CREATE TABLE TBL_ASIGNATURAS
(
   CODIGO_ASIGNATURA INT NOT NULL AUTO_INCREMENT,
   CODIGO_ALTERNO VARCHAR(200),
   NOMBRE_ASIGNATURA VARCHAR(400),
   CANTIDAD_UNIDADES_VALORATIVAS INT,
   DIAS VARCHAR(200),
   CODIGO_CARRERA INT NOT NULL,
   CODIGO_TIPO_ASIGNATURA INT NOT NULL,
   CONSTRAINT TBL_ASIGNATURAS_PK PRIMARY KEY(CODIGO_ASIGNATURA)
);


CREATE TABLE TBL_AULAS
(
   CODIGO_AULA INT NOT NULL AUTO_INCREMENT,
   NUMERO_AULA VARCHAR(100) NOT NULL,
   CODIGO_TIPO_AULA INT NOT NULL,
   CODIGO_EDIFICIO INT NOT NULL,
   CONSTRAINT TBL_AULAS_PK PRIMARY KEY(CODIGO_AULA)
);


CREATE TABLE TBL_CAMPUS
(
   CODIGO_CAMPUS INT NOT NULL AUTO_INCREMENT,
   NOMBRE_CAMPUS VARCHAR(200) NOT NULL,
   CONSTRAINT TBL_CAMPUS_PK PRIMARY KEY(CODIGO_CAMPUS)
);


CREATE TABLE TBL_CARGOS
(
   CODIGO_CARGO INT NOT NULL AUTO_INCREMENT,
   CODIGO_CARGO_SUPERIOR INT,
   NOMBRE_CARGO VARCHAR(200),
   CONSTRAINT TBL_CARGOS_PK PRIMARY KEY(CODIGO_CARGO)
);


CREATE TABLE TBL_CARRERAS
(
   CODIGO_CARRERA INT NOT NULL AUTO_INCREMENT,
   CODIGO_AUXILIAR VARCHAR(20) NOT NULL,
   CODIGO_FACULTAD INT NOT NULL,
   NOMBRE_CARRERA VARCHAR(200),
   CANTIDAD_ASIGNATURAS INT NOT NULL,
   CANTIDAD_UNIDADES_VALORATIVAS INT,
   CODIGO_GRADO INT NOT NULL,
   CONSTRAINT TBL_CARRERAS_PK PRIMARY KEY(CODIGO_CARRERA)
);

CREATE TABLE TBL_CARRERAS_X_ALUMNOS
(
   CODIGO_CARRERA INT NOT NULL AUTO_INCREMENT,
   CODIGO_ALUMNO INT NOT NULL,
   FECHA_REGISTRO_CARRERA DATETIME NOT NULL,
   PROMEDIO_CARRERA DOUBLE,
   CANTIDAD_CLASES_APROBADAS INT,
   CONSTRAINT TBL_CARRERAS_X_ALUMNOS_PK PRIMARY KEY(CODIGO_CARRERA,CODIGO_ALUMNO)
);


CREATE TABLE TBL_DETALLE_EVALUACION
(
   CODIGO_HISTORIAL INT NOT NULL,
   CODIGO_TIPO_EVALUACION INT NOT NULL,
   VALOR_NOTA DOUBLE NOT NULL
);

CREATE TABLE TBL_EDIFICIOS
(
   CODIGO_EDIFICIO INT NOT NULL AUTO_INCREMENT,
   NOMBRE_EDIFICIO VARCHAR(200),
   ALIAS_EDIFICIO VARCHAR(200),
   CODIGO_CAMPUS INT NOT NULL,
   CONSTRAINT TBL_EDIFICIOS_PK PRIMARY KEY(CODIGO_EDIFICIO)
);


CREATE TABLE TBL_EMPLEADOS
(
   CODIGO_EMPLEADO INT NOT NULL AUTO_INCREMENT,
   NUMERO_EMPLEADO INT NOT NULL,
   SUELDO_BASE DOUBLE NOT NULL,
   CODIGO_TIPO_EMPLEADO INT NOT NULL,
   CODIGO_CARGO INT NOT NULL,
   CONTRASENA VARCHAR(30),
   CONSTRAINT TBL_EMPLEADOS_PK PRIMARY KEY(CODIGO_EMPLEADO)
);


CREATE TABLE TBL_ESTADOS_CIVILES
(
   CODIGO_ESTADO_CIVIL INT NOT NULL AUTO_INCREMENT,
   NOMBRE_ESTADO_CIVIL VARCHAR(200) NOT NULL,
   CONSTRAINT TBL_ESTADOS_CIVILES_PK PRIMARY KEY(CODIGO_ESTADO_CIVIL)
);


CREATE TABLE TBL_ESTADOS_MATRICULA
(
   CODIGO_ESTADO_MATRICULA INT NOT NULL AUTO_INCREMENT, 
   NOMBRE_ESTADO VARCHAR(200),
   DESCRIPCION VARCHAR(200),
   CONSTRAINT TBL_ESTADOS_MATRICULA_PK PRIMARY KEY(CODIGO_ESTADO_MATRICULA)
);


CREATE TABLE TBL_FACULTADES
(
   CODIGO_FACULTAD INT NOT NULL AUTO_INCREMENT,
   NOMBRE_FACULTAD VARCHAR(200),
   DESCRIPCION VARCHAR(200),
   CONSTRAINT TBL_FACULTADES_PK PRIMARY KEY(CODIGO_FACULTAD)
);

CREATE TABLE TBL_GENEROS
(
   CODIGO_GENERO INT NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR UNICO PARA EL CAMPO GENERO',
   NOMBRE_GENERO VARCHAR(60) NOT NULL,
   ABREVIATURA VARCHAR(10),
   CONSTRAINT TBL_GENEROS_PK PRIMARY KEY(CODIGO_GENERO)
);
/* Comment statement is commented since its functionality is implemented in Create Table. */
/*COMMENT ON COLUMN TBL_GENEROS.CODIGO_GENERO
IS
  'IDENTIFICADOR UNICO PARA EL CAMPO GENERO' ;*/
CREATE TABLE TBL_GRADOS
(
   CODIGO_GRADO INT NOT NULL AUTO_INCREMENT,
   NOMBRE_GRADO VARCHAR(200) NOT NULL,
   CONSTRAINT TBL_GRADOS_PK PRIMARY KEY(CODIGO_GRADO)
);


CREATE TABLE TBL_HISTORIAL
(
   CODIGO_HISTORIAL INT NOT NULL AUTO_INCREMENT,
   CODIGO_ALUMNO INT NOT NULL,
   CODIGO_SECCION INT NOT NULL,
   CODIGO_PERIODO INT NOT NULL,
   PROMEDIO DOUBLE NOT NULL,
   CONSTRAINT TBL_HISTORIAL_PK PRIMARY KEY(CODIGO_HISTORIAL)
);


CREATE TABLE TBL_LUGARES
(
   CODIGO_LUGAR INT NOT NULL AUTO_INCREMENT,
   NOMBRE_LUGAR VARCHAR(200) NOT NULL,
   LONGITUD DOUBLE,
   LATITUD DOUBLE,
   CODIGO_TIPO_LUGAR INT NOT NULL,
   CODIGO_LUGAR_PADRE INT,
   CONSTRAINT TBL_LUGARES_PK PRIMARY KEY(CODIGO_LUGAR)
);


CREATE TABLE TBL_MAESTROS
(
   CODIGO_MAESTRO INT NOT NULL AUTO_INCREMENT,
   CODIGO_ESPECIALIZACION INT NOT NULL,
   CODIGO_TITULARIDAD INT NOT NULL,
   CONSTRAINT TBL_MAESTROS_PK PRIMARY KEY(CODIGO_MAESTRO)
);


CREATE TABLE TBL_MATRICULA
(
   FECHA_MATRICULA DATETIME,
   CODIGO_SECCION INT NOT NULL,
   CODIGO_ALUMNO INT NOT NULL,
   CODIGO_ESTADO_MATRICULA INT NOT NULL
);

CREATE TABLE TBL_PERIODOS
(
   CODIGO_PERIODO INT NOT NULL AUTO_INCREMENT,
   NOMBRE_PERIODO VARCHAR(200),
   FECHA_INICIO DATETIME,
   FECHA_FIN DATETIME,
   CODIGO_TIPO_PERIODO INT NOT NULL,
   CONSTRAINT TBL_PERIODOS_PK PRIMARY KEY(CODIGO_PERIODO)
);


CREATE TABLE TBL_PERSONAS
(
   CODIGO_PERSONA INT NOT NULL AUTO_INCREMENT,
   CODIGO_GENERO INT NOT NULL,
   CODIGO_LUGAR_NACIMIENTO INT NOT NULL,
   CODIGO_LUGAR_RESIDENCIA INT NOT NULL,
   CODIGO_MUNICIPIO_NACIMIENTO INT NOT NULL,
   CODIGO_MUNICIPIO_RESIDENCIA INT NOT NULL,
   CODIGO_CAMPUS INT NOT NULL,
   CODIGO_TIPO_IDENTIFICACION INT NOT NULL,
   CODIGO_ESTADO_CIVIL INT NOT NULL,
   NOMBRE VARCHAR(200) NOT NULL,
   APELLIDO VARCHAR(200) NOT NULL,
   FECHA_NACIMIENTO DATETIME NOT NULL,
   IDENTIDAD VARCHAR(15) NOT NULL,
   DIRECCION VARCHAR(800) NOT NULL,
   TELEFONO VARCHAR(30) NOT NULL,
   CORREO_ELECTRONICO VARCHAR(300) NOT NULL,
   CONSTRAINT TBL_PERSONAS_PK PRIMARY KEY(CODIGO_PERSONA)
);

CREATE TABLE TBL_REQUISITOS
(
   CODIGO_ASIGNATURA INT NOT NULL,
   CODIGO_ASIGNATURA_REQUISITO INT,
   CODIGO_CARRERA INT NOT NULL
);
CREATE INDEX TBL_REQUISITOS__IDX ON TBL_REQUISITOS
(CODIGO_ASIGNATURA ASC,
CODIGO_ASIGNATURA_REQUISITO ASC,
CODIGO_CARRERA ASC);

CREATE TABLE TBL_SECCION
(
   CODIGO_SECCION INT NOT NULL AUTO_INCREMENT,
   CODIGO_ALTERNO VARCHAR(200) NOT NULL,
   HORA_INICIO DATETIME,
   HORA_FIN DATETIME,
   DIAS VARCHAR(200),
   CODIGO_AULA INT NOT NULL,
   CODIGO_ASIGNATURA INT NOT NULL,
   CODIGO_MAESTRO INT NOT NULL,
   CODIGO_PERIODO INT NOT NULL,
   CANTIDAD_CUPOS INT,
   CONSTRAINT TBL_SECCION_PK PRIMARY KEY(CODIGO_SECCION)
);


CREATE TABLE TBL_TIPOS_AULAS
(
   CODIGO_TIPO_AULA INT AUTO_INCREMENT NOT NULL,
   TIPO_AULA VARCHAR(200) NOT NULL,
   DESCRIPCION VARCHAR(200),
   CONSTRAINT TBL_TIPOS_AULAS_PK PRIMARY KEY(CODIGO_TIPO_AULA)
);


CREATE TABLE TBL_TIPOS_EVALUACIONES
(
   CODIGO_TIPO_EVALUACION INT NOT NULL AUTO_INCREMENT,
   NOMBRE_TIPO_EVALUACION VARCHAR(200),
   CONSTRAINT TBL_TIPOS_EVALUACIONES_PK PRIMARY KEY(CODIGO_TIPO_EVALUACION)
);


CREATE TABLE TBL_TIPOS_PERIODOS
(
   CODIGO_TIPO_PERIODO INT NOT NULL AUTO_INCREMENT  COMMENT 'Campo que identifica de forma unica un tipo de periodo',
   TIPO_PERIODO VARCHAR(200),
   CONSTRAINT TBL_TIPOS_PERIODOS_PK PRIMARY KEY(CODIGO_TIPO_PERIODO)
);

CREATE TABLE TBL_TIPO_ASIGNATURA
(
   CODIGO_TIPO_ASIGNATURA INT NOT NULL,
   TIPO_ASIGNATURA VARCHAR(250),
   CONSTRAINT TBL_TIPO_ASIGNATURA_PK PRIMARY KEY(CODIGO_TIPO_ASIGNATURA)
);


CREATE TABLE TBL_TIPO_EMPLEADO
(
   CODIGO_TIPO_EMPLEADO INT NOT NULL AUTO_INCREMENT,
   NOMBRE_TIPO_EMPLEADO VARCHAR(200),
   CONSTRAINT TBL_TIPO_EMPLEADO_PK PRIMARY KEY(CODIGO_TIPO_EMPLEADO)
);


CREATE TABLE TBL_TIPO_IDENTIFICACION
(
   CODIGO_TIPO_IDENTIFICACION INT NOT NULL AUTO_INCREMENT,
   TIPO_IDENTIFICACION VARCHAR(200) NOT NULL,
   CONSTRAINT TBL_TIPO_IDENTIFICACION_PK PRIMARY KEY(CODIGO_TIPO_IDENTIFICACION)
);


CREATE TABLE TBL_TIPO_LUGARES
(
   CODIGO_TIPO_LUGAR INT AUTO_INCREMENT NOT NULL ,
   NOMBRE_TIPO_LUGAR VARCHAR(200) NOT NULL,
   CONSTRAINT TBL_TIPO_LUGAR_PK PRIMARY KEY(CODIGO_TIPO_LUGAR)
);

CREATE TABLE TBL_TITULARIDAD
(
   CODIGO_TITULARIDAD INT AUTO_INCREMENT NOT NULL ,
   NOMBRE_TITULARIDAD VARCHAR(200),
   SALARIO_MINIMO DOUBLE,
   SALARIO_MAXIMO DOUBLE,
   CONSTRAINT TBL_TITULARIDAD_PK PRIMARY KEY(CODIGO_TITULARIDAD)
);


CREATE TABLE TBL_TITULOS
(
   CODIGO_TITULO INT AUTO_INCREMENT NOT NULL,
   NOMBRE_TITULO varchar(300),
   CONSTRAINT TBL_TITULOS_PK PRIMARY KEY(CODIGO_TITULO)
    
);


CREATE TABLE TBL_TITULOS_X_EMPLEADO
(
   CODIGO_TITULO INT NOT NULL,
   CODIGO_EMPLEADO INT NOT NULL,
   CODIGO_UNIVERSIDAD INT NOT NULL,
   FECHA DATETIME,
   NUMERO_REGISTRO VARCHAR(200),
   CONSTRAINT TBL_TITULOS_X_EMPLEADO_PK PRIMARY KEY(CODIGO_TITULO,CODIGO_EMPLEADO)
);


CREATE TABLE TBL_UNIVERSIDADES
(
   CODIGO_UNIVERSIDAD INT AUTO_INCREMENT NOT NULL,
   NOMBRE_UNIVERSIDAD varchar(300)
   
    ,
   DIRECCION varchar(300)
   
    ,
   TELEFONO varchar(300),
   CONSTRAINT TBL_UNIVERSIDADES_PK PRIMARY KEY(CODIGO_UNIVERSIDAD)
  
);

ALTER TABLE TBL_PERSONAS ADD CONSTRAINT TBL_ALUMNOS_TBL_CAMPUS_FK FOREIGN KEY(CODIGO_CAMPUS) REFERENCES TBL_CAMPUS(CODIGO_CAMPUS);


ALTER TABLE TBL_PERSONAS ADD CONSTRAINT TBL_ALUMNOS_TBL_ESTADOS_CIVILES_FK FOREIGN KEY(CODIGO_ESTADO_CIVIL) REFERENCES TBL_ESTADOS_CIVILES(CODIGO_ESTADO_CIVIL);

ALTER TABLE TBL_PERSONAS ADD CONSTRAINT TBL_ALUMNOS_TBL_GENEROS_FK FOREIGN KEY(CODIGO_GENERO) REFERENCES TBL_GENEROS(CODIGO_GENERO);

ALTER TABLE TBL_PERSONAS ADD CONSTRAINT TBL_ALUMNOS_TBL_LUGARES_FK FOREIGN KEY(CODIGO_LUGAR_NACIMIENTO) REFERENCES TBL_LUGARES(CODIGO_LUGAR);

ALTER TABLE TBL_PERSONAS ADD CONSTRAINT TBL_ALUMNOS_TBL_LUGARES_FKV1 FOREIGN KEY(CODIGO_LUGAR_RESIDENCIA) REFERENCES TBL_LUGARES(CODIGO_LUGAR);

ALTER TABLE TBL_ALUMNOS ADD CONSTRAINT TBL_ALUMNOS_TBL_PERSONAS_FK FOREIGN KEY(CODIGO_ALUMNO) REFERENCES TBL_PERSONAS(CODIGO_PERSONA);


ALTER TABLE TBL_PERSONAS ADD CONSTRAINT TBL_ALUMNOS_TBL_TIPO_IDENTIFICACION_FK FOREIGN KEY(CODIGO_TIPO_IDENTIFICACION) REFERENCES TBL_TIPO_IDENTIFICACION(CODIGO_TIPO_IDENTIFICACION);


ALTER TABLE TBL_ASIGNATURAS ADD CONSTRAINT TBL_ASIGNATURAS_TBL_CARRERAS_FK FOREIGN KEY(CODIGO_CARRERA) REFERENCES TBL_CARRERAS(CODIGO_CARRERA);


ALTER TABLE TBL_ASIGNATURAS ADD CONSTRAINT TBL_ASIGNATURAS_TBL_TIPO_ASIGNATURA_FK FOREIGN KEY(CODIGO_TIPO_ASIGNATURA) REFERENCES TBL_TIPO_ASIGNATURA(CODIGO_TIPO_ASIGNATURA);

ALTER TABLE TBL_AULAS ADD CONSTRAINT TBL_AULAS_TBL_EDIFICIOS_FK FOREIGN KEY(CODIGO_EDIFICIO) REFERENCES TBL_EDIFICIOS(CODIGO_EDIFICIO);

ALTER TABLE TBL_AULAS ADD CONSTRAINT TBL_AULAS_TBL_TIPOS_AULAS_FK FOREIGN KEY(CODIGO_TIPO_AULA) REFERENCES TBL_TIPOS_AULAS(CODIGO_TIPO_AULA);

ALTER TABLE TBL_CARGOS ADD CONSTRAINT TBL_CARGOS_TBL_CARGOS_FK FOREIGN KEY(CODIGO_CARGO_SUPERIOR) REFERENCES TBL_CARGOS(CODIGO_CARGO);

ALTER TABLE TBL_CARRERAS ADD CONSTRAINT TBL_CARRERAS_TBL_FACULTADES_FK FOREIGN KEY(CODIGO_FACULTAD) REFERENCES TBL_FACULTADES(CODIGO_FACULTAD);

ALTER TABLE TBL_CARRERAS ADD CONSTRAINT TBL_CARRERAS_TBL_GRADOS_FK FOREIGN KEY(CODIGO_GRADO) REFERENCES TBL_GRADOS(CODIGO_GRADO);


ALTER TABLE TBL_CARRERAS_X_ALUMNOS ADD CONSTRAINT TBL_CARRERAS_X_ALUMNOS_TBL_ALUMNOS_FK FOREIGN KEY(CODIGO_ALUMNO) REFERENCES TBL_PERSONAS(CODIGO_PERSONA);


ALTER TABLE TBL_CARRERAS_X_ALUMNOS ADD CONSTRAINT TBL_CARRERAS_X_ALUMNOS_TBL_CARRERAS_FK FOREIGN KEY(CODIGO_CARRERA) REFERENCES TBL_CARRERAS(CODIGO_CARRERA);


ALTER TABLE TBL_DETALLE_EVALUACION ADD CONSTRAINT TBL_DETALLE_EVALUACION_TBL_HISTORIAL_FK FOREIGN KEY(CODIGO_HISTORIAL) REFERENCES TBL_HISTORIAL(CODIGO_HISTORIAL);


ALTER TABLE TBL_DETALLE_EVALUACION ADD CONSTRAINT TBL_DETALLE_EVALUACION_TBL_TIPOS_EVALUACIONES_FK FOREIGN KEY(CODIGO_TIPO_EVALUACION) REFERENCES TBL_TIPOS_EVALUACIONES(CODIGO_TIPO_EVALUACION);

ALTER TABLE TBL_EDIFICIOS ADD CONSTRAINT TBL_EDIFICIOS_TBL_CAMPUS_FK FOREIGN KEY(CODIGO_CAMPUS) REFERENCES TBL_CAMPUS(CODIGO_CAMPUS);

ALTER TABLE TBL_EMPLEADOS ADD CONSTRAINT TBL_EMPLEADOS_TBL_CARGOS_FK FOREIGN KEY(CODIGO_CARGO) REFERENCES TBL_CARGOS(CODIGO_CARGO);

ALTER TABLE TBL_EMPLEADOS ADD CONSTRAINT TBL_EMPLEADOS_TBL_PERSONAS_FK FOREIGN KEY(CODIGO_EMPLEADO) REFERENCES TBL_PERSONAS(CODIGO_PERSONA);


ALTER TABLE TBL_EMPLEADOS ADD CONSTRAINT TBL_EMPLEADOS_TBL_TIPO_EMPLEADO_FK FOREIGN KEY(CODIGO_TIPO_EMPLEADO) REFERENCES TBL_TIPO_EMPLEADO(CODIGO_TIPO_EMPLEADO);

ALTER TABLE TBL_HISTORIAL ADD CONSTRAINT TBL_HISTORIAL_TBL_ALUMNOS_FK FOREIGN KEY(CODIGO_ALUMNO) REFERENCES TBL_ALUMNOS(CODIGO_ALUMNO);

ALTER TABLE TBL_HISTORIAL ADD CONSTRAINT TBL_HISTORIAL_TBL_PERIODOS_FK FOREIGN KEY(CODIGO_PERIODO) REFERENCES TBL_PERIODOS(CODIGO_PERIODO);

ALTER TABLE TBL_HISTORIAL ADD CONSTRAINT TBL_HISTORIAL_TBL_SECCION_FK FOREIGN KEY(CODIGO_SECCION) REFERENCES TBL_SECCION(CODIGO_SECCION);

ALTER TABLE TBL_LUGARES ADD CONSTRAINT TBL_LUGARES_TBL_LUGARES_FK FOREIGN KEY(CODIGO_LUGAR_PADRE) REFERENCES TBL_LUGARES(CODIGO_LUGAR);


ALTER TABLE TBL_LUGARES ADD CONSTRAINT TBL_LUGARES_TBL_TIPO_LUGARES_FK FOREIGN KEY(CODIGO_TIPO_LUGAR) REFERENCES TBL_TIPO_LUGARES(CODIGO_TIPO_LUGAR);


ALTER TABLE TBL_MAESTROS ADD CONSTRAINT TBL_MAESTROS_TBL_AREA_ESPECIALIZACIONES_FK FOREIGN KEY(CODIGO_ESPECIALIZACION) REFERENCES TBL_AREA_ESPECIALIZACIONES(CODIGO_ESPECIALIZACION);

ALTER TABLE TBL_MAESTROS ADD CONSTRAINT TBL_MAESTROS_TBL_EMPLEADOS_FK FOREIGN KEY(CODIGO_MAESTRO) REFERENCES TBL_EMPLEADOS(CODIGO_EMPLEADO);


ALTER TABLE TBL_MAESTROS ADD CONSTRAINT TBL_MAESTROS_TBL_TITULARIDAD_FK FOREIGN KEY(CODIGO_TITULARIDAD) REFERENCES TBL_TITULARIDAD(CODIGO_TITULARIDAD);

ALTER TABLE TBL_MATRICULA ADD CONSTRAINT TBL_MATRICULA_TBL_ALUMNOS_FK FOREIGN KEY(CODIGO_ALUMNO) REFERENCES TBL_ALUMNOS(CODIGO_ALUMNO);


ALTER TABLE TBL_MATRICULA ADD CONSTRAINT TBL_MATRICULA_TBL_ESTADOS_MATRICULA_FK FOREIGN KEY(CODIGO_ESTADO_MATRICULA) REFERENCES TBL_ESTADOS_MATRICULA(CODIGO_ESTADO_MATRICULA);

ALTER TABLE TBL_MATRICULA ADD CONSTRAINT TBL_MATRICULA_TBL_SECCION_FK FOREIGN KEY(CODIGO_SECCION) REFERENCES TBL_SECCION(CODIGO_SECCION);


ALTER TABLE TBL_PERIODOS ADD CONSTRAINT TBL_PERIODOS_TBL_TIPOS_PERIODOS_FK FOREIGN KEY(CODIGO_TIPO_PERIODO) REFERENCES TBL_TIPOS_PERIODOS(CODIGO_TIPO_PERIODO);


ALTER TABLE TBL_REQUISITOS ADD CONSTRAINT TBL_REQUISITOS_TBL_ASIGNATURAS_FK FOREIGN KEY(CODIGO_ASIGNATURA) REFERENCES TBL_ASIGNATURAS(CODIGO_ASIGNATURA);


ALTER TABLE TBL_REQUISITOS ADD CONSTRAINT TBL_REQUISITOS_TBL_ASIGNATURAS_FKV1 FOREIGN KEY(CODIGO_ASIGNATURA_REQUISITO) REFERENCES TBL_ASIGNATURAS(CODIGO_ASIGNATURA);

ALTER TABLE TBL_REQUISITOS ADD CONSTRAINT TBL_REQUISITOS_TBL_CARRERAS_FK FOREIGN KEY(CODIGO_CARRERA) REFERENCES TBL_CARRERAS(CODIGO_CARRERA);

ALTER TABLE TBL_SECCION ADD CONSTRAINT TBL_SECCION_TBL_ASIGNATURAS_FK FOREIGN KEY(CODIGO_ASIGNATURA) REFERENCES TBL_ASIGNATURAS(CODIGO_ASIGNATURA);

ALTER TABLE TBL_SECCION ADD CONSTRAINT TBL_SECCION_TBL_AULAS_FK FOREIGN KEY(CODIGO_AULA) REFERENCES TBL_AULAS(CODIGO_AULA);

ALTER TABLE TBL_SECCION ADD CONSTRAINT TBL_SECCION_TBL_MAESTROS_FK FOREIGN KEY(CODIGO_MAESTRO) REFERENCES TBL_MAESTROS(CODIGO_MAESTRO);

ALTER TABLE TBL_SECCION ADD CONSTRAINT TBL_SECCION_TBL_PERIODOS_FK FOREIGN KEY(CODIGO_PERIODO) REFERENCES TBL_PERIODOS(CODIGO_PERIODO);


ALTER TABLE TBL_TITULOS_X_EMPLEADO ADD CONSTRAINT TBL_TITULOS_X_EMPLEADO_TBL_EMPLEADOS_FK FOREIGN KEY(CODIGO_EMPLEADO) REFERENCES TBL_EMPLEADOS(CODIGO_EMPLEADO);


ALTER TABLE TBL_TITULOS_X_EMPLEADO ADD CONSTRAINT TBL_TITULOS_X_EMPLEADO_TBL_TITULOS_FK FOREIGN KEY(CODIGO_TITULO) REFERENCES TBL_TITULOS(CODIGO_TITULO);
